In [25]:
import pandas as pd
import sqlite3
import os
from sqlalchemy import create_engine

conn = sqlite3.connect('test_database')
c = conn.cursor()

c.execute('''CREATE TABLE IF NOT EXISTS products (
    Rank INT,
    `Name of Company` TEXT,
    `Location` TEXT,
    `FY2021_retail_revenue` TEXT,
    `FY2021_parent_company/ group revenue` TEXT,
    `Dominant_operational_format` TEXT,
    `Geographies_of_operation` TEXT,
    `FY2016-2021_retail_revenueCAGR3` TEXT,
    `FY2020-2021_retail_revenue_growth` TEXT,
    `FY2021_Net_profit_margin` TEXT)
    ''')

conn.commit()


df = pd.read_csv('/home/muregz/data_analysis/RetailAnalysis/leading_retailers_2021.csv', encoding='Windows-1252')


df.isna().sum()
 #if any null values drop or impute

df.dropna(inplace = True)
df

# Remove commas from string values in 'FY2021_retail_revenue' column
df['FY2021_retail_revenue'] = df['FY2021_retail_revenue'].str.replace(',', '')

# Convert column to integer type
df['FY2021_retail_revenue'] = df['FY2021_retail_revenue'].astype(int)



df.to_sql('products', conn, if_exists='replace', index = False)
 
c.execute('''  
SELECT * FROM products
          ''')
conn.commit()

In [ ]:
#configuring mysql into jupyter notebook
%load_ext sql
%config SqlMagic.autopandas=True

In [ ]:
#connecting the database
# Construct the connection URL
db_url = f"sqlite:///{os.path.abspath('/home/muregz/data_analysis/RetailAnalysis/test_database')}"

# Set the DATABASE_URL environment variable
os.environ['DATABASE_URL'] = db_url

# Create a database engine
engine = create_engine(os.environ['DATABASE_URL'])

In [26]:
%%sql
SELECT * FROM products;

 * sqlite:////home/muregz/data_analysis/RetailAnalysis/test_database.db
Done.

,Rank,Name of Company,Location,FY2021_retail_revenue,FY2021_parent_company/ group revenue,Dominant_operational_format,Geographies_of_operation,FY2016- 2021_retail_revenueCAGR3,FY2020-2021_retail_revenue_growth,FY2021_Net_profit_margin
0,1,Walmart Inc,United States,"5,72,754","5,72,754",Hypermarket/ supercenter,24,3.30%,2.40%,2.40%
1,2,"Amazon.com, Inc.",United States,"2,39,150","4,69,822",Non-store,21,20.40%,12.00%,7.10%
2,3,Costco Wholesale Corporation,United States,"1,95,929","1,95,929",Cash & carry/ warehouse club,12,10.50%,17.50%,2.60%
3,4,Schwarz Group,Germany,"1,53,754","1,56,209",Discount store,33,7.80%,5.50%,None
4,5,"The Home Depot, Inc",United States,"1,51,157","1,51,157",Home improvement,3,9.80%,14.40%,10.90%
...,...,...,...,...,...,...,...,...,...,...
245,246,EG Group Limited,United Kingdom,"4,606","26,420",Convenience/ forecourt store,10,75.10%,4.30%,n/a
246,247,"Yaoko Co., Ltd.",Japan,"4,575","4,771",Supermarket,1,9.40%,5.50%,2.90%
247,248,"Daiso Industries Co., Ltd",Japan,"4,546","4,889",Discount department store,26,5.50%,4.40%,n/a
248,249,Shufersal Ltd.,Israel,"4,544","4,561",Discount store,1,4.60%,-3.10%,2.70%
249,250,T. J. Morris dba Home Bargains,United Kingdom,"4,478","4,478",Other specialty,1,15.80%,19.60%,9.50%

In [ ]:
print(df['FY2021_retail_revenue'].describe())

In [ ]:
%%sql
--showing the different operational formats from the retailers
SELECT DISTINCT Dominant_operational_format FROM products;